news: add linux install party 2023
ustclug/website pull request #35
Opened 2023-04-04 15:07 UTC by zig-one

2023-04-04 15:13 UTC, taoky commented on Gemfile
> +gem "webrick", "~> 1.8"
这个依赖是？

2023-04-04 16:17 UTC, iBug commented on Gemfile
> +gem "webrick", "~> 1.8"
本地 preview 用的，是个 http server

2023-04-04 16:18 UTC, taoky commented on Gemfile
> +gem "webrick", "~> 1.8"
新版 jekyll (4.2.3) 应该会带这个依赖，不用手动指定了。

2023-04-05 02:30 UTC, bc-li requested changes

2023-04-05 02:30 UTC, bc-li commented on Gemfile
> +gem "webrick", "~> 1.8"
加个 commit 把这个删掉吧

2023-04-09 04:42 UTC, bc-li requested changes

2023-04-09 04:42 UTC, bc-li commented on README.md
> +3. 如果需要预览则需要安装 `webrick` ，但是不需要将 `Gemfile` 中的更改提交至仓库
不需要修改文档吧？根据 https://github.com/ustclug/website/pull/35#discussion_r1157488167 新版 jekyll 已经带这个依赖了。

2023-04-09 04:48 UTC, zig-one commented
现在的 Gemfile 里的 jekyll 还是老版本，上次没有安装 webrick 的时候无法预览，是否需要提高版本？

2023-04-09 04:50 UTC, iBug commented on Gemfile
> +gem "webrick", "~> 1.8"
我查了一下，问题出在 Ruby 上，Ruby 2.x 自带 webrick 作为标准库，Ruby 3.0 把它删了，所以 Ruby 3.0+ 需要手动指定依赖。

以及 Jekyll 没有 4.2.3 这个版本，倒是 4.3.0 把 webrick 加进 dependency 里了。

2023-04-09 05:13 UTC, bc-li commented on pages/_news/2023/2023-4-2-Linux_Install_Party_2023.md
> +很多同学在使用虚拟机体验 Linux 之后决定腾出硬盘空间来安装双系统。在确认相应分区无重要数据后，使用 Windows 的压缩卷功能腾出用来安装的空间。随后在 BIOS 中关闭安全启动并选择使用 U 盘引导，最后在 Ventoy 的列表中选择相应发行版的安装镜像就能进行相应的安装。
话说这样做是否标准

2023-04-09 05:34 UTC, merged