Create 2024-6-6-geant4-ubuntu-install
ustclug/website pull request #75
Opened 2024-06-06 12:26 UTC by zyh1206

The following are some of the experiences I have summarized from my learning of the Linux system, and I hope these experiences can help future learners

2024-06-06 12:30 UTC, taoky commented
Markdown 格式有一些散乱，并且 CI 检查未通过。可以修改一下吗？

2024-06-06 12:33 UTC, zyh1206 commented
我看了一下，好像是jekyll-archives插件不兼容，请问你知道这个怎么处理吗

2024-06-06 12:38 UTC, bc-li commented
> 我看了一下，好像是jekyll-archives插件不兼容，请问你知道这个怎么处理吗

是不是 markdown 头没写 date 呀，你可以参照一下其他页面的配置看一下自己的格式

2024-06-06 12:40 UTC, iBug commented
应该是文件名的 date 格式要 2024-06-06，月和日不能只写一个数字吧

2024-06-06 12:42 UTC, zyh1206 commented
现在修改了，看起来还有点问题？

2024-06-06 12:43 UTC, bc-li commented
> 文件名的 date 格式要 2024-06-06

@zyh1206 这个不是修改 PR title，是要修改你提交的文件名，修改之后再 push 一次吧

2024-06-06 12:43 UTC, taoky commented
> 现在修改了，看起来还有点问题？

你修改的是 PR 的标题，而不是新建的文件的文件名。

如果无法搞定的话，我可以帮助做一些基本的修复。

2024-06-06 13:27 UTC, zyh1206 commented
真的谢谢了

2024-06-06 13:55 UTC, taoky requested changes

2024-06-06 13:55 UTC, taoky commented on pages/_planet/2024-06-06-geant4-ubuntu-install.md
> +本文用于分享本人在使用 Ubuntu 系统参与科研工作时，安装 geant4 软件包的经历，希望可以为新学习者提供帮助，更好的入手专业软件的学习与应用。
可以在开头介绍一下你自己吗？

2024-06-06 13:55 UTC, taoky commented on pages/_planet/2024-06-06-geant4-ubuntu-install.md
> +   sudo sed -i 's/cn.archive.ubuntu.com/mirrors.aliyun.com/g' /etc/apt/sources.list
请修改为使用科大源。

2024-06-06 13:55 UTC, taoky commented on pages/_planet/2024-06-06-geant4-ubuntu-install.md
> +   geant4 的资源可以在 <https://geant4.web.cern.ch/download/11.2.1.html> 中下载得到，如果工具正常安装，可以将 Windows 文件转移到虚拟机中
> 如果工具正常安装，可以将 Windows 文件转移到虚拟机中

这句话的逻辑是不太通顺的。

2024-06-06 13:55 UTC, taoky commented on pages/_planet/2024-06-06-geant4-ubuntu-install.md
> +      sudo apt install qt5* -y
> `sudo apt install qt5* -y`

这看起来不太合理，建议具体指出是哪些 qt5 的依赖。

2024-06-06 13:55 UTC, taoky commented on pages/_planet/2024-06-06-geant4-ubuntu-install.md
> +      sudo apt install curl g++ libgl1-mesa-dev cmake libx11-dev libxext-dev libxtst-dev libxrender-dev libxmu-dev  libxmuu-dev libhdf5-serial-dev hdf5-tools libexpat1 libexpat1-dev build-essential -
```suggestion
      sudo apt install curl g++ libgl1-mesa-dev cmake libx11-dev libxext-dev libxtst-dev libxrender-dev libxmu-dev libxmuu-dev libhdf5-serial-dev hdf5-tools libexpat1 libexpat1-dev build-essential -y
```

2024-06-06 13:55 UTC, taoky commented on pages/_planet/2024-06-06-geant4-ubuntu-install.md
> +      sudo gedit ~/.bashrc
> `sudo gedit ~/.bashrc`

这条命令显然假设了环境带有桌面环境，并且不是在标准的 SSH 的场合下。这个软件是只需要在个人电脑上运行吗？

2024-06-06 13:55 UTC, taoky commented on pages/_planet/2024-06-06-geant4-ubuntu-install.md
> +   sudo ls *.tar.gz | sudo xargs -n1 tar xzvf
`ls` 也要 `sudo`？

2024-06-06 13:55 UTC, taoky commented on pages/_planet/2024-06-06-geant4-ubuntu-install.md
> +      sudo mv geant4/ /opt/
我的建议是，最开始新建文件夹之后，修改所有者到你自己，这样后续步骤就都不需要 `sudo` 了。

2024-06-06 13:58 UTC, taoky commented
附：如果使用 git 存在困难，可以直接回复上面的修改意见，不要再新开 PR。

2024-06-11 06:37 UTC, taoky commented
https://blog.csdn.net/zsd234/article/details/138164185

如果 CSDN 上 https://blog.csdn.net/zsd234 不是你的话，这个 PR 是无法接受的。**请不要抄袭其他人的内容**。

2024-06-12 11:07 UTC, taoky commented
由于接近一周没有得到任何回复，https://github.com/ustclug/website/pull/75#issuecomment-2159909021 中提及的抄袭问题也未得到回应，此 PR 关闭。

2024-06-12 11:07 UTC, closed without merging