feat(news): add 2024-09-07-2024-freshmen-course
ustclug/website pull request #86
Opened 2024-09-11 14:37 UTC by tiankaima

2024-09-11 16:29 UTC, ustcljh commented on pages/_news/2024/2024-09-07-2024-freshmen-course.md
> +在活动的下半场，罗嘉宏同学为大家讲解了 GNUplot、LaTeX 等工具的使用，他通过实例演示了如何使用这些工具来绘制图表、排版文档等，使同学们对这些工具有了初步的了解。
GNUPlot 拼写

2024-09-11 16:30 UTC, ustcljh commented on pages/_news/2024/2024-09-07-2024-freshmen-course.md
> +9 月 7 日新生活力课堂的上半场是由王昊元同学带来的《日常生活中的信息安全〉, 他从信息安全的基本概念出发，为新同学们讲解了信息安全的重要性，并介绍了一些常见的信息安全问题，如密码安全，钓鱼邮件等，以及相应的防范措施。他进一步拓展到了公钥密码学、ARP Spoofing、XSS、SQL Injection 等内容，使同学们对信息安全有了更深入的了解。
左右书名号不匹配

2024-09-11 16:31 UTC, ustcljh commented on pages/_news/2024/2024-09-07-2024-freshmen-course.md
> +![](https://ftp.lug.ustc.edu.cn/%E6%B4%BB%E5%8A%A8/2024.09.08_%E6%96%B0%E7%94%9F%E6%B4%BB%E5%8A%9B%E8%AF%BE%E5%A0%82/AB9A2077.jpeg)
配图是 ygy 不是 why

2024-09-11 16:33 UTC, ustcljh requested changes
请调整一下做了 comments 的地方，many thanks

2024-09-12 02:26 UTC, MirageTurtle requested changes
如果统一 09.07 的话，直接把我改成 ygy 也可以我觉得，这样配图也没什么问题了，只是录屏好像只有 09.08 的录屏。

2024-09-12 02:26 UTC, MirageTurtle commented on pages/_news/2024/2024-09-07-2024-freshmen-course.md
> +9 月 7 日新生活力课堂的上半场是由王昊元同学带来的《日常生活中的信息安全〉, 他从信息安全的基本概念出发，为新同学们讲解了信息安全的重要性，并介绍了一些常见的信息安全问题，如密码安全，钓鱼邮件等，以及相应的防范措施。他进一步拓展到了公钥密码学、ARP Spoofing、XSS、SQL Injection 等内容，使同学们对信息安全有了更深入的了解。
「公钥密码学」改成「密码学」吧。

2024-09-12 02:26 UTC, MirageTurtle commented on pages/_news/2024/2024-09-07-2024-freshmen-course.md
> +- [09.07 活动录屏](https://ftp.lug.ustc.edu.cn/%E6%B4%BB%E5%8A%A8/2024.09.08_%E6%96%B0%E7%94%9F%E6%B4%BB%E5%8A%9B%E8%AF%BE%E5%A0%82/20240908185437-USTCLUG%20%E6%96%B0%E7%94%9F%E6%B4%BB%E5%8A%9B%E8%AF%BE%
录屏应该是 09.08，是吧？ @ustcljh

2024-09-12 02:31 UTC, ustcljh commented on pages/_news/2024/2024-09-07-2024-freshmen-course.md
> +- [09.07 活动录屏](https://ftp.lug.ustc.edu.cn/%E6%B4%BB%E5%8A%A8/2024.09.08_%E6%96%B0%E7%94%9F%E6%B4%BB%E5%8A%9B%E8%AF%BE%E5%A0%82/20240908185437-USTCLUG%20%E6%96%B0%E7%94%9F%E6%B4%BB%E5%8A%9B%E8%AF%BE%
对的，是东区那场

2024-09-12 05:31 UTC, merged